services:
  network_simulation:
    build: .
    network_mode: "host"
    privileged: true # Required for Mininet and Open vSwitch
    ports:
      - "6633:6633" # Expose the OpenFlow port for Ryu controller
    environment:
      CONTROLLER_IP: "127.0.0.1"
      CONTROLLER_PORT: "6633"
    volumes:
      - .:/app # Mount the current directory to /app inside the container
    command: bash -c "service openvswitch-switch start && ryu-manager src/controller/ryu_controller.py & python src/main.py"
